# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Advantage 360'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["adv360pro_left","adv360pro_right"]'
